apiVersion: v1
kind: Service
metadata: 
  name: springboot-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service